.TH "can_core.c" 3 "14 Sep 2001" "can4linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
can_core.c \-  
.SH SYNOPSIS
.br
.PP
.SS Variables

.in +1c
.ti -1c
.RI "struct file_operations \fBcan_fops\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
 
.PP
\fBAuthor(s): \fR
.in +1c
Heinz-Jürgen Oertel, port GmbH 
.PP
\fBRevision: \fR
.in +1c
 1.3  
.PP
\fBDate: \fR
.in +1c
 2001/09/04 15:51:44 
.PP
Contains the code for module initialization. The functions herein are never called directly by the user but when the driver module is loaded into the kernel space or unloaded.
.PP
The driver is highly configurable using the \fBsysctl\fR interface. For a description see main page.
.PP
.SH VARIABLE DOCUMENTATION
.PP 
.SS struct file_operations can_fops
.PP
\fBInitial value:\fR
.PP
.nf
 { 



    lseek:      NULL, 

    read:       can_read,
    write:      can_write,
    readdir:    NULL, 



    select:     can_select,

    ioctl:      can_ioctl,
    mmap:       NULL, 
    open:       can_open,


 
    release:    can_close,
    fsync:      NULL,
    fasync:     NULL,
}
.fi
.SH AUTHOR
.PP 
Generated automatically by Doxygen for can4linux from the source code.