.TH "can_write.c" 3 "11 Sep 2003" "can4linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
can_write.c \-  
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "__LDDK_WRITE_TYPE \fBcan_write\fP (__LDDK_WRITE_PARAM)"
.br
.RI "\fIsize_t write(int fd, const char *buf, size_t count); write CAN messages to the network\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
 
.PP
\fBAuthor: \fP
.in +1c
Heinz-Jürgen Oertel, port GmbH 
.PP
\fBRevision: \fP
.in +1c
 1.7  
.PP
\fBDate: \fP
.in +1c
 2003/07/05 14:28:55 
.PP
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "__LDDK_WRITE_TYPE can_write (__LDDK_WRITE_PARAM)"
.PP
size_t write(int fd, const char *buf, size_t count); write CAN messages to the network
.PP
\fBParameters: \fP
.in +1c
.TP
\fB\fIfd\fP\fP
The descriptor to write to. 
.TP
\fB\fIbuf\fP\fP
The data buffer to write (array of CAN \fBcanmsg_t\fP). 
.TP
\fB\fIcount\fP\fP
The number of bytes to write.write writes up to \fIcount\fP CAN messages to the CAN controller referenced by the file descriptor fd from the buffer starting at buf.
.PP
\fBErrors\fP
.in +1c
the following errors can occur
.TP
 \fCEBADF\fP fd is not a valid file descriptor or is not open for writing.
.PP
.TP
 \fCEINVAL\fP fd is attached to an object which is unsuitable for writing.
.PP
.TP
 \fCEFAULT\fP buf is outside your accessible address space.
.PP
.TP
 \fCEINTR\fP The call was interrupted by a signal before any data was written.
.PP
\fBReturns: \fP
.in +1c
On success, the number of CAN messages written are returned (zero indicates nothing was written). On error, -1 is returned, and errno is set appropriately. 
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for can4linux from the source code.
