.TH "can_close.c" 3 "14 Sep 2001" "can4linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
can_close.c \-  
.SH SYNOPSIS
.br
.PP
.SS Functions

.in +1c
.ti -1c
.RI "__LDDK_CLOSE_TYPE \fBcan_close\fR (__LDDK_CLOSE_PARAM)"
.br
.RI "\fIint close(int fd); close a file descriptor.\fR"
.in -1c
.SS Variables

.in +1c
.ti -1c
.RI "int \fBCan_isopen\fR []"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
 
.PP
\fBAuthor(s): \fR
.in +1c
Heinz-Jürgen Oertel, port GmbH 
.PP
\fBRevision: \fR
.in +1c
 1.3  
.PP
\fBDate: \fR
.in +1c
 2001/09/04 15:50:57 
.PP
.SH FUNCTION DOCUMENTATION
.PP 
.SS __LDDK_CLOSE_TYPE can_close (__LDDK_CLOSE_PARAM)
.PP
int close(int fd); close a file descriptor.
.PP
\fBParameters: \fR
.in +1c
.TP
\fB\fIfd\fR\fR
The descriptor to close.
.PP
\fBclose\fR closes a file descriptor, so that it no longer refers to any device and may be reused. 
.PP
\fBReturns: \fR
.in +1c
close returns zero on success, or -1 if an error occurred. 
.PP
\fBERRORS\fR
.in +1c
the following errors can occur
.PP
.TP
 \fCBADF\fR \fBfd\fR isn't a valid open file descriptor 
.SH AUTHOR
.PP 
Generated automatically by Doxygen for can4linux from the source code.