.TH "CanSja1000Status_par" 3 "27 Aug 2003" "can4linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CanSja1000Status_par \- IOCTL CAN controller status request parameter structure. 

.PP
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBbaud\fP"
.br
.RI "\fIactual bit rate\fP"
.ti -1c
.RI "unsigned char \fBstatus\fP"
.br
.RI "\fICAN controller status register.\fP"
.ti -1c
.RI "unsigned int \fBerror_warning_limit\fP"
.br
.RI "\fIthe error warning limit\fP"
.ti -1c
.RI "unsigned int \fBrx_errors\fP"
.br
.RI "\fIcontent of RX error counter\fP"
.ti -1c
.RI "unsigned int \fBtx_errors\fP"
.br
.RI "\fIcontent of TX error counter\fP"
.ti -1c
.RI "unsigned int \fBerror_code\fP"
.br
.RI "\fIcontent of error code register\fP"
.ti -1c
.RI "unsigned int \fBrx_buffer_size\fP"
.br
.RI "\fIsize of rx buffer\fP"
.ti -1c
.RI "unsigned int \fBrx_buffer_used\fP"
.br
.RI "\fInumber of messages\fP"
.ti -1c
.RI "unsigned int \fBtx_buffer_size\fP"
.br
.RI "\fIsize of tx buffer\fP"
.ti -1c
.RI "unsigned int \fBtx_buffer_used\fP"
.br
.RI "\fInumber of messages\fP"
.ti -1c
.RI "unsigned long \fBretval\fP"
.br
.RI "\fIreturn value\fP"
.in -1c
.SH "Detailed Description"
.PP 
IOCTL CAN controller status request parameter structure.

.SH "Author"
.PP 
Generated automatically by Doxygen for can4linux from the source code.
