.TH "Command_par" 3 "1 Dec 2002" "can4linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Command_par \- IOCTL Command request parameter structure. 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcmd\fP"
.br
.RI "\fIspecial driver command\fP"
.ti -1c
.RI "int \fBerror\fP"
.br
.RI "\fIreturn value\fP"
.ti -1c
.RI "unsigned long \fBretval\fP"
.br
.RI "\fIreturn value\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
IOCTL Command request parameter structure.
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for can4linux from the source code.
