.TH "ConfigureRTR_par" 3 "14 Sep 2001" "can4linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigureRTR_par \- IOCTL ConfigureRTR request parameter structure. 
.SH SYNOPSIS
.br
.PP
\fC#include <can.h>\fR
.PP
.SS Data Fields

.in +1c
.ti -1c
.RI "unsigned \fBmessage\fR"
.br
.RI "\fICAN message ID.\fR"
.ti -1c
.RI "\fBcanmsg_t\fR* \fBTx\fR"
.br
.RI "\fICAN message struct.\fR"
.ti -1c
.RI "int \fBerror\fR"
.br
.RI "\fIreturn value for errno.\fR"
.ti -1c
.RI "unsigned long \fBretval\fR"
.br
.RI "\fIreturn value.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
IOCTL ConfigureRTR request parameter structure.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for can4linux from the source code.