.TH "Config_par" 3 "11 Sep 2003" "can4linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Config_par \- IOCTL Configuration request parameter structure. 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtarget\fP"
.br
.RI "\fIspecial configuration target\fP"
.ti -1c
.RI "unsigned long \fBval1\fP"
.br
.RI "\fI1\fP"
.ti -1c
.RI "unsigned long \fBval2\fP"
.br
.RI "\fI2\fP"
.ti -1c
.RI "int \fBerror\fP"
.br
.RI "\fIreturn value for errno\fP"
.ti -1c
.RI "unsigned long \fBretval\fP"
.br
.RI "\fIreturn value\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
IOCTL Configuration request parameter structure.
.PP
.SH "FIELD DOCUMENTATION"
.PP 
.SS "unsigned long Config_par::val1"
.PP
1
.PP
parameter for the target 
.SS "unsigned long Config_par::val2"
.PP
2
.PP
parameter for the target 

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for can4linux from the source code.
